/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techcoffee;

import java.awt.Color;
import javax.swing.JPanel;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author kobao
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        //setUndecorated(true);
        initComponents();
        connectDB();
        jLayeredMain.removeAll();
        hienthi();
        
    }

    Connection conn;
    PreparedStatement pSm;
    ResultSet rs;

    public void connectDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/techcoffee?" + "user=root&password=000001");
            pSm = conn.prepareCall("SELECT * from users where username=? and passwd=? and check_admin=?");
            System.out.print("Connect is success");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Server error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    public void switchPanel(JPanel panel) {
        jLayeredMain.removeAll();
        jLayeredMain.add(panel);
        jLayeredMain.repaint();
        jLayeredMain.revalidate();
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usernamelogin = new javax.swing.JLabel();
        jLayeredMain = new javax.swing.JLayeredPane();
        jPanelthemNV = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        getHoten = new javax.swing.JTextField();
        getsdt = new javax.swing.JTextField();
        getNgaysinh = new javax.swing.JTextField();
        getID = new javax.swing.JTextField();
        getNgayVaolam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        getMucLuong = new javax.swing.JTextField();
        btnNhapLai = new javax.swing.JButton();
        btnXacnhanThemNV = new javax.swing.JButton();
        jPanelHienThi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelcapnhatNV = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        setHoten = new javax.swing.JTextField();
        setsdt = new javax.swing.JTextField();
        setNgaysinh = new javax.swing.JTextField();
        setID = new javax.swing.JTextField();
        setNgayVaoLam = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        setMucLuong = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        setIDNew = new javax.swing.JTextField();
        btnXacNhanCapnhatNV = new javax.swing.JButton();
        jPanelhienthiBandadat = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        setYeuCauKhachdatban = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        sobandat = new javax.swing.JLabel();
        songuoidat = new javax.swing.JLabel();
        jPanelXoaNV = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        setHotenXoa = new javax.swing.JTextField();
        setsdtXoa = new javax.swing.JTextField();
        setNgaysinhXoa = new javax.swing.JTextField();
        setIDXoa = new javax.swing.JTextField();
        setNgayVaoLamXoa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        setMucLuongXoa = new javax.swing.JTextField();
        btnXacNhanCapnhatNV1 = new javax.swing.JButton();
        jPanellichSu = new javax.swing.JPanel();
        btndelete_history = new javax.swing.JButton();
        btnadd_history = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelfeedback = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        settimeFeedback = new javax.swing.JLabel();
        setusername = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        setfeedback = new javax.swing.JTextArea();
        setidFeelback = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanelNhanVien = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnlichsu = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btncapnhatnv = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btnathemnv = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnxoanv = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnHienthi = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnfeedback = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        bnt_logout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonBandadat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(32, 90, 180));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-user.png"))); // NOI18N

        usernamelogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        usernamelogin.setForeground(new java.awt.Color(204, 204, 0));
        usernamelogin.setText("USERNAME");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamelogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(usernamelogin))
                    .addComponent(jLabel3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 80));

        jPanelthemNV.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Họ tên: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Ngày vào làm: ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Số điện thoại:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Mức lương: ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("ID:");

        btnNhapLai.setBackground(new java.awt.Color(0, 0, 0));
        btnNhapLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNhapLai.setForeground(new java.awt.Color(204, 204, 0));
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhapLaiMouseClicked(evt);
            }
        });
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });

        btnXacnhanThemNV.setBackground(new java.awt.Color(0, 0, 0));
        btnXacnhanThemNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacnhanThemNV.setForeground(new java.awt.Color(204, 204, 0));
        btnXacnhanThemNV.setText("Xác Nhận");
        btnXacnhanThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacnhanThemNVMouseClicked(evt);
            }
        });
        btnXacnhanThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacnhanThemNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelthemNVLayout = new javax.swing.GroupLayout(jPanelthemNV);
        jPanelthemNV.setLayout(jPanelthemNVLayout);
        jPanelthemNVLayout.setHorizontalGroup(
            jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelthemNVLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelthemNVLayout.createSequentialGroup()
                        .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getNgaysinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getHoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelthemNVLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelthemNVLayout.createSequentialGroup()
                        .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelthemNVLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(getNgayVaolam, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelthemNVLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(getMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelthemNVLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelthemNVLayout.createSequentialGroup()
                                .addComponent(btnXacnhanThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanelthemNVLayout.setVerticalGroup(
            jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelthemNVLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getHoten, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(getNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(getsdt, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(getNgayVaolam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(getMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(23, 23, 23)
                .addGroup(jPanelthemNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacnhanThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(565, 565, 565))
        );

        jPanelHienThi.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Họ tên", "Ngày sinh", "số điện thoại", "Ngày vào làm", "Mức lương", "ID"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Ngày vào làm");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Mức lương");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("ID");
        }

        javax.swing.GroupLayout jPanelHienThiLayout = new javax.swing.GroupLayout(jPanelHienThi);
        jPanelHienThi.setLayout(jPanelHienThiLayout);
        jPanelHienThiLayout.setHorizontalGroup(
            jPanelHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        jPanelHienThiLayout.setVerticalGroup(
            jPanelHienThiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelcapnhatNV.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Họ tên: ");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Ngày sinh:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Ngày vào làm: ");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Số điện thoại:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Mức lương: ");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("ID:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("ID New:");

        btnXacNhanCapnhatNV.setBackground(new java.awt.Color(0, 0, 0));
        btnXacNhanCapnhatNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacNhanCapnhatNV.setForeground(new java.awt.Color(204, 204, 0));
        btnXacNhanCapnhatNV.setText("Cập nhật ");
        btnXacNhanCapnhatNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanCapnhatNVMouseClicked(evt);
            }
        });
        btnXacNhanCapnhatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanCapnhatNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelcapnhatNVLayout = new javax.swing.GroupLayout(jPanelcapnhatNV);
        jPanelcapnhatNV.setLayout(jPanelcapnhatNVLayout);
        jPanelcapnhatNVLayout.setHorizontalGroup(
            jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(setID, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setIDNew, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(setNgaysinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(setHoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(setsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(setNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(btnXacNhanCapnhatNV, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanelcapnhatNVLayout.setVerticalGroup(
            jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelcapnhatNVLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setHoten, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(setNgaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(setsdt, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(setNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(setMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelcapnhatNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel16))
                    .addGroup(jPanelcapnhatNVLayout.createSequentialGroup()
                        .addComponent(setID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(setIDNew, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnXacNhanCapnhatNV, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        jPanelhienthiBandadat.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Thứ ", "Số bàn", "Username", "Số người", "Thời gian đặt bàn", "Yêu cầu thêm"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable4);

        setYeuCauKhachdatban.setColumns(20);
        setYeuCauKhachdatban.setLineWrap(true);
        setYeuCauKhachdatban.setRows(5);
        jScrollPane6.setViewportView(setYeuCauKhachdatban);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setText("Yêu cầu của khác hàng ");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setText("Bàn đặt:");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("Số người:");

        javax.swing.GroupLayout jPanelhienthiBandadatLayout = new javax.swing.GroupLayout(jPanelhienthiBandadat);
        jPanelhienthiBandadat.setLayout(jPanelhienthiBandadatLayout);
        jPanelhienthiBandadatLayout.setHorizontalGroup(
            jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelhienthiBandadatLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelhienthiBandadatLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelhienthiBandadatLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(songuoidat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel24))
                    .addGroup(jPanelhienthiBandadatLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(sobandat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelhienthiBandadatLayout.setVerticalGroup(
            jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelhienthiBandadatLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(sobandat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelhienthiBandadatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(songuoidat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        jPanelXoaNV.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Họ tên: ");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Ngày sinh:");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Ngày vào làm: ");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("Số điện thoại:");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("Mức lương: ");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("ID:");

        btnXacNhanCapnhatNV1.setBackground(new java.awt.Color(0, 0, 0));
        btnXacNhanCapnhatNV1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXacNhanCapnhatNV1.setForeground(new java.awt.Color(204, 204, 0));
        btnXacNhanCapnhatNV1.setText("Xác nhận xóa");
        btnXacNhanCapnhatNV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanCapnhatNV1MouseClicked(evt);
            }
        });
        btnXacNhanCapnhatNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanCapnhatNV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelXoaNVLayout = new javax.swing.GroupLayout(jPanelXoaNV);
        jPanelXoaNV.setLayout(jPanelXoaNVLayout);
        jPanelXoaNVLayout.setHorizontalGroup(
            jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(setIDXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setMucLuongXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(setNgaysinhXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(setHotenXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(setsdtXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(setNgayVaoLamXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanelXoaNVLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnXacNhanCapnhatNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanelXoaNVLayout.setVerticalGroup(
            jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelXoaNVLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setHotenXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(setNgaysinhXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(setsdtXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(setNgayVaoLamXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(setMucLuongXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelXoaNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setIDXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(btnXacNhanCapnhatNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        jPanellichSu.setBackground(new java.awt.Color(255, 255, 255));

        btndelete_history.setBackground(new java.awt.Color(0, 0, 0));
        btndelete_history.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete_history.setForeground(new java.awt.Color(204, 204, 0));
        btndelete_history.setText("Lịch sử xóa");
        btndelete_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndelete_historyMouseClicked(evt);
            }
        });
        btndelete_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_historyActionPerformed(evt);
            }
        });

        btnadd_history.setBackground(new java.awt.Color(0, 0, 0));
        btnadd_history.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd_history.setForeground(new java.awt.Color(204, 204, 0));
        btnadd_history.setText("Lịch sử thêm");
        btnadd_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnadd_historyMouseClicked(evt);
            }
        });
        btnadd_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_historyActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Lưu", "ID nhân viên", "Trạng thái", "Thời gian"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanellichSuLayout = new javax.swing.GroupLayout(jPanellichSu);
        jPanellichSu.setLayout(jPanellichSuLayout);
        jPanellichSuLayout.setHorizontalGroup(
            jPanellichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellichSuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnadd_history, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btndelete_history, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jPanellichSuLayout.setVerticalGroup(
            jPanellichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellichSuLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanellichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd_history, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_history, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jPanelfeedback.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Feelback", "USERNAME", "feedback", "Time"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        setfeedback.setColumns(20);
        setfeedback.setLineWrap(true);
        setfeedback.setRows(5);
        setfeedback.setToolTipText("");
        jScrollPane4.setViewportView(setfeedback);

        jLabel4.setText("ID Feedback:");

        jLabel5.setText("USERNAME:");

        jLabel23.setText("ID Feedback:");

        javax.swing.GroupLayout jPanelfeedbackLayout = new javax.swing.GroupLayout(jPanelfeedback);
        jPanelfeedback.setLayout(jPanelfeedbackLayout);
        jPanelfeedbackLayout.setHorizontalGroup(
            jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                        .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(setusername, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(setidFeelback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(settimeFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanelfeedbackLayout.setVerticalGroup(
            jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                            .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(setidFeelback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(45, 45, 45))
                        .addGroup(jPanelfeedbackLayout.createSequentialGroup()
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelfeedbackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(setusername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(settimeFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredMainLayout = new javax.swing.GroupLayout(jLayeredMain);
        jLayeredMain.setLayout(jLayeredMainLayout);
        jLayeredMainLayout.setHorizontalGroup(
            jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredMainLayout.createSequentialGroup()
                .addComponent(jPanelthemNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelHienThi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelhienthiBandadat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelcapnhatNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanellichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredMainLayout.setVerticalGroup(
            jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelthemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelhienthiBandadat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelcapnhatNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 415, Short.MAX_VALUE)))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 415, Short.MAX_VALUE)))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanellichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredMainLayout.createSequentialGroup()
                    .addComponent(jPanelfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredMain.setLayer(jPanelthemNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanelHienThi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanelcapnhatNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanelhienthiBandadat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanelXoaNV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanellichSu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanelfeedback, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.add(jLayeredMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 710, 500));

        jPanelNhanVien.setBackground(new java.awt.Color(32, 90, 180));

        jPanel4.setBackground(new java.awt.Color(32, 90, 180));

        btnlichsu.setBackground(new java.awt.Color(0, 0, 0));
        btnlichsu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnlichsu.setForeground(new java.awt.Color(204, 204, 0));
        btnlichsu.setText("Lịch sử thay đổi");
        btnlichsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlichsuMouseClicked(evt);
            }
        });
        btnlichsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlichsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlichsu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlichsu, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(32, 90, 180));

        btncapnhatnv.setBackground(new java.awt.Color(0, 0, 0));
        btncapnhatnv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncapnhatnv.setForeground(new java.awt.Color(204, 204, 0));
        btncapnhatnv.setText("Cập nhật nhân viên");
        btncapnhatnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncapnhatnvMouseClicked(evt);
            }
        });
        btncapnhatnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btncapnhatnv, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btncapnhatnv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(32, 90, 180));

        btnathemnv.setBackground(new java.awt.Color(0, 0, 0));
        btnathemnv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnathemnv.setForeground(new java.awt.Color(204, 204, 0));
        btnathemnv.setText("Thêm nhân viên");
        btnathemnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnathemnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(btnathemnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnathemnv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(32, 90, 180));

        btnxoanv.setBackground(new java.awt.Color(0, 0, 0));
        btnxoanv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnxoanv.setForeground(new java.awt.Color(204, 204, 0));
        btnxoanv.setText("Xóa nhân viên");
        btnxoanv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnxoanvMouseClicked(evt);
            }
        });
        btnxoanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoanvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnxoanv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnxoanv, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(32, 90, 180));

        btnHienthi.setBackground(new java.awt.Color(0, 0, 0));
        btnHienthi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHienthi.setForeground(new java.awt.Color(204, 204, 0));
        btnHienthi.setText("Hiển thị nhân viên");
        btnHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHienthi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHienthi, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(32, 90, 180));

        btnfeedback.setBackground(new java.awt.Color(0, 0, 0));
        btnfeedback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfeedback.setForeground(new java.awt.Color(204, 204, 0));
        btnfeedback.setText("Feedback Khách hàng");
        btnfeedback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfeedbackMouseClicked(evt);
            }
        });
        btnfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnfeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelNhanVienLayout = new javax.swing.GroupLayout(jPanelNhanVien);
        jPanelNhanVien.setLayout(jPanelNhanVienLayout);
        jPanelNhanVienLayout.setHorizontalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelNhanVienLayout.setVerticalGroup(
            jPanelNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhanVienLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 420));

        jPanel12.setBackground(new java.awt.Color(32, 90, 180));

        bnt_logout.setBackground(new java.awt.Color(204, 204, 0));
        bnt_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-logout.png"))); // NOI18N
        bnt_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnt_logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bnt_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(bnt_logout)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 70, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 960, 530));

        jPanel3.setBackground(new java.awt.Color(32, 90, 180));

        jButtonBandadat.setBackground(new java.awt.Color(0, 0, 0));
        jButtonBandadat.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButtonBandadat.setForeground(new java.awt.Color(204, 204, 0));
        jButtonBandadat.setText("Bàn đã đặt");
        jButtonBandadat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBandadatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonBandadat, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonBandadat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 710, 50));

        jPanel2.setBackground(new java.awt.Color(32, 90, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlichsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlichsuActionPerformed

    }//GEN-LAST:event_btnlichsuActionPerformed

    private void btncapnhatnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatnvActionPerformed

    }//GEN-LAST:event_btncapnhatnvActionPerformed

    private void btnathemnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnathemnvActionPerformed
        switchPanel(jPanelthemNV);
    }//GEN-LAST:event_btnathemnvActionPerformed

    private void btnxoanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxoanvActionPerformed

    private void btnHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienthiActionPerformed
        switchPanel(jPanelHienThi);
        try {
            pSm = conn.prepareStatement("SELECT * from employee");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("emplyeename"), rs.getString("birthday"), rs.getString("phonenumber"), rs.getString("workingday"), rs.getString("wage"), rs.getString("idemployee")};
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btnHienthiActionPerformed

    private void btnfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfeedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfeedbackActionPerformed

    private void btncapnhatnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncapnhatnvMouseClicked
        switchPanel(jPanelcapnhatNV);
        setIDNew.setText("");

    }//GEN-LAST:event_btncapnhatnvMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        setHoten.setText(model.getValueAt(i, 0).toString());
        setNgaysinh.setText(model.getValueAt(i, 1).toString());
        setsdt.setText(model.getValueAt(i, 2).toString());
        setNgayVaoLam.setText(model.getValueAt(i, 3).toString());
        setMucLuong.setText(model.getValueAt(i, 4).toString());
        setID.setText(model.getValueAt(i, 5).toString());

        setHotenXoa.setText(model.getValueAt(i, 0).toString());
        setNgaysinhXoa.setText(model.getValueAt(i, 1).toString());
        setsdtXoa.setText(model.getValueAt(i, 2).toString());
        setNgayVaoLamXoa.setText(model.getValueAt(i, 3).toString());
        setMucLuongXoa.setText(model.getValueAt(i, 4).toString());
        setIDXoa.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnxoanvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnxoanvMouseClicked
        switchPanel(jPanelXoaNV);

    }//GEN-LAST:event_btnxoanvMouseClicked

    private void btnXacnhanThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacnhanThemNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacnhanThemNVActionPerformed

    private void btnXacnhanThemNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacnhanThemNVMouseClicked
        try {
            pSm = conn.prepareStatement("call add_employee(?,?,?,?,?,?)");
            pSm.setString(1, getID.getText());
            pSm.setString(2, getHoten.getText());
            pSm.setString(3, getsdt.getText());
            pSm.setString(4, getMucLuong.getText());
            pSm.setString(5, getNgayVaolam.getText());
            pSm.setString(6, getNgaysinh.getText());
            if (!getID.getText().isEmpty() && !getHoten.getText().isEmpty() && !getsdt.getText().isEmpty() && !getMucLuong.getText().isEmpty() && !getNgayVaolam.getText().isEmpty() && !getNgaysinh.getText().isEmpty()) {
                pSm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Them thanh cong");
            } else {
                JOptionPane.showMessageDialog(null, "Them that bai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID bi trung ! Xin nhap ID khac");
        }
    }//GEN-LAST:event_btnXacnhanThemNVMouseClicked

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void btnNhapLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapLaiMouseClicked
        getID.setText("");
        getHoten.setText("");
        getsdt.setText("");
        getMucLuong.setText("");
        getNgayVaolam.setText("");
        getNgaysinh.setText("");
    }//GEN-LAST:event_btnNhapLaiMouseClicked

    private void btnXacNhanCapnhatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanCapnhatNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanCapnhatNVActionPerformed

    private void btnXacNhanCapnhatNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanCapnhatNVMouseClicked
        try {

            pSm = conn.prepareCall("call update_employee(?,?,?,?,?,?,?)");
            if (setIDNew.getText().isEmpty()) {
                setIDNew.setText(setID.getText());
            }

            pSm.setString(1, setIDNew.getText());
            pSm.setString(2, setHoten.getText());
            pSm.setString(3, setsdt.getText());
            pSm.setString(4, setMucLuong.getText());
            pSm.setString(5, setNgayVaoLam.getText());
            pSm.setString(6, setNgaysinh.getText());
            pSm.setString(7, setID.getText());

            if (!setID.getText().isEmpty() && !setHoten.getText().isEmpty() && !setsdt.getText().isEmpty() && !setMucLuong.getText().isEmpty() && !setNgayVaoLam.getText().isEmpty() && !setNgaysinh.getText().isEmpty()) {
                pSm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Cap nhat thanh cong");
            } else {
                JOptionPane.showMessageDialog(null, "Cap nhat that bai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ID bi trung ! Xin nhap ID khac");
        }

    }//GEN-LAST:event_btnXacNhanCapnhatNVMouseClicked

    private void btnXacNhanCapnhatNV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanCapnhatNV1MouseClicked
        try {

            pSm = conn.prepareCall("call delete_employee(?)");
            pSm.setString(1, setIDXoa.getText());

            if (!setIDXoa.getText().isEmpty()) {
                pSm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Xoa thanh cong");
            } else {
                JOptionPane.showMessageDialog(null, "Xoa that bai do ID trong");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Xoa that bai");
        }
    }//GEN-LAST:event_btnXacNhanCapnhatNV1MouseClicked

    private void btnXacNhanCapnhatNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanCapnhatNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanCapnhatNV1ActionPerformed

    private void btndelete_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndelete_historyMouseClicked
        try {

            pSm = conn.prepareStatement("SELECT * from save_delete");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("idsave_delete"), rs.getString("idemployee_savedelete"), rs.getString("statuses"), rs.getString("date")};
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btndelete_historyMouseClicked

    private void btndelete_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndelete_historyActionPerformed

    private void btnadd_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnadd_historyMouseClicked
        try {

            pSm = conn.prepareStatement("SELECT * from save_add");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("idsave_add"), rs.getString("idemployee_saveadd"), rs.getString("statuses"), rs.getString("date")};
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btnadd_historyMouseClicked

    private void btnadd_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadd_historyActionPerformed

    private void btnlichsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlichsuMouseClicked
        switchPanel(jPanellichSu);

    }//GEN-LAST:event_btnlichsuMouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        int i = jTable3.getSelectedRow();
        TableModel model = jTable3.getModel();
        setidFeelback.setText(model.getValueAt(i, 0).toString());
        setusername.setText(model.getValueAt(i, 1).toString());
        setfeedback.setText(model.getValueAt(i, 2).toString());
        settimeFeedback.setText(model.getValueAt(i,3).toString());
        setidFeelback.setForeground(Color.red);
        setusername.setForeground(Color.red);
        settimeFeedback.setForeground(Color.red);
        
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnfeedbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfeedbackMouseClicked
        switchPanel(jPanelfeedback);
        try {

            pSm = conn.prepareStatement("SELECT * from feedback");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("idfeedback"), rs.getString("userNameF"), rs.getString("noiDung"),rs.getString("TimeF")}; 
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }//GEN-LAST:event_btnfeedbackMouseClicked

    private void bnt_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnt_logoutMouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_bnt_logoutMouseClicked

    private void jButtonBandadatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBandadatMouseClicked
        switchPanel(jPanelhienthiBandadat);
        try {
            pSm = conn.prepareStatement("SELECT * from datBan");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("idDatban"), rs.getString("soBan"), rs.getString("userName"),rs.getString("soNguoi"),rs.getString("timeDatban"),rs.getString("yeuCau")}; 
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonBandadatMouseClicked

    public void hienthi(){
        switchPanel(jPanelhienthiBandadat);
        try {
            pSm = conn.prepareStatement("SELECT * from datBan");
            rs = pSm.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
            tm.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getString("idDatban"), rs.getString("soBan"), rs.getString("userName"),rs.getString("soNguoi"),rs.getString("timeDatban"),rs.getString("yeuCau")}; 
                tm.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error" + e.getMessage());
        }
    }
    
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        int i = jTable4.getSelectedRow();
        TableModel model = jTable4.getModel();
        setYeuCauKhachdatban.setText(model.getValueAt(i, 5).toString());
        songuoidat.setText(model.getValueAt(i, 3).toString());
        sobandat.setText(model.getValueAt(i, 1).toString());
        songuoidat.setForeground(Color.red);
        sobandat.setForeground(Color.red);
    }//GEN-LAST:event_jTable4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_logout;
    private javax.swing.JButton btnHienthi;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnXacNhanCapnhatNV;
    private javax.swing.JButton btnXacNhanCapnhatNV1;
    private javax.swing.JButton btnXacnhanThemNV;
    private javax.swing.JButton btnadd_history;
    private javax.swing.JButton btnathemnv;
    private javax.swing.JButton btncapnhatnv;
    private javax.swing.JButton btndelete_history;
    private javax.swing.JButton btnfeedback;
    private javax.swing.JButton btnlichsu;
    private javax.swing.JButton btnxoanv;
    private javax.swing.JTextField getHoten;
    private javax.swing.JTextField getID;
    private javax.swing.JTextField getMucLuong;
    private javax.swing.JTextField getNgayVaolam;
    private javax.swing.JTextField getNgaysinh;
    private javax.swing.JTextField getsdt;
    private javax.swing.JButton jButtonBandadat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelHienThi;
    private javax.swing.JPanel jPanelNhanVien;
    private javax.swing.JPanel jPanelXoaNV;
    private javax.swing.JPanel jPanelcapnhatNV;
    private javax.swing.JPanel jPanelfeedback;
    private javax.swing.JPanel jPanelhienthiBandadat;
    private javax.swing.JPanel jPanellichSu;
    private javax.swing.JPanel jPanelthemNV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField setHoten;
    private javax.swing.JTextField setHotenXoa;
    private javax.swing.JTextField setID;
    private javax.swing.JTextField setIDNew;
    private javax.swing.JTextField setIDXoa;
    private javax.swing.JTextField setMucLuong;
    private javax.swing.JTextField setMucLuongXoa;
    private javax.swing.JTextField setNgayVaoLam;
    private javax.swing.JTextField setNgayVaoLamXoa;
    private javax.swing.JTextField setNgaysinh;
    private javax.swing.JTextField setNgaysinhXoa;
    private javax.swing.JTextArea setYeuCauKhachdatban;
    private javax.swing.JTextArea setfeedback;
    private javax.swing.JLabel setidFeelback;
    private javax.swing.JTextField setsdt;
    private javax.swing.JTextField setsdtXoa;
    private javax.swing.JLabel settimeFeedback;
    private javax.swing.JLabel setusername;
    private javax.swing.JLabel sobandat;
    private javax.swing.JLabel songuoidat;
    public static javax.swing.JLabel usernamelogin;
    // End of variables declaration//GEN-END:variables
}
