/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package techcoffee;

/**
 *
 * @author kobao
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class Login extends javax.swing.JFrame {

    public static String usernamee;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        connectDB();
        this.setLocationRelativeTo(null);

    }

    Connection conn;
    PreparedStatement pSm;
    ResultSet rs;

    public void switchPanel(JPanel panel) {
        Container.removeAll();
        Container.add(panel);
        Container.repaint();
        Container.revalidate();

    }

    public void connectDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost/techcoffee?" + "user=root&password=000001");
            System.out.print("Connect is success");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Server error");
        }
    }

    //getuser name 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        Panellogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Panelsignup = new javax.swing.JPanel();
        lbUsernameSignup = new javax.swing.JTextField();
        lbPassSignup2 = new javax.swing.JPasswordField();
        lbPassSignup = new javax.swing.JPasswordField();
        btnSignup = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setLayout(new java.awt.CardLayout());

        Panellogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-user-login .png"))); // NOI18N
        Panellogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/ic-lock -login.png"))); // NOI18N
        Panellogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        username.setBackground(new java.awt.Color(255, 204, 102));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Panellogin.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 180, 30));

        passwd.setBackground(new java.awt.Color(255, 204, 102));
        passwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwdKeyPressed(evt);
            }
        });
        Panellogin.add(passwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 180, 30));

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/log-in.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Panellogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 50, -1));

        jLabel4.setBackground(new java.awt.Color(255, 153, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText(" No account? Create new account");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Panellogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 350, 40));

        jLabel5.setBackground(new java.awt.Color(255, 153, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        Panellogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/background_login1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        Panellogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        Container.add(Panellogin, "card3");

        Panelsignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsernameSignup.setBackground(new java.awt.Color(255, 204, 102));
        lbUsernameSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbUsernameSignupActionPerformed(evt);
            }
        });
        Panelsignup.add(lbUsernameSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 180, 30));

        lbPassSignup2.setBackground(new java.awt.Color(255, 204, 102));
        lbPassSignup2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbPassSignup2KeyPressed(evt);
            }
        });
        Panelsignup.add(lbPassSignup2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 180, 30));

        lbPassSignup.setBackground(new java.awt.Color(255, 204, 102));
        lbPassSignup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbPassSignupKeyPressed(evt);
            }
        });
        Panelsignup.add(lbPassSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 180, 30));

        btnSignup.setBackground(new java.awt.Color(255, 153, 0));
        btnSignup.setText("Sign Up");
        btnSignup.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignupMouseClicked(evt);
            }
        });
        Panelsignup.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nhập Lại Mật Khẩu :");
        Panelsignup.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mật Khẩu  :");
        Panelsignup.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên Tài Khoản : ");
        Panelsignup.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 30));

        jLabel8.setBackground(new java.awt.Color(255, 153, 51));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Click here go to login !");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        Panelsignup.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 250, 40));

        jLabel9.setBackground(new java.awt.Color(255, 153, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        Panelsignup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/techcoffee/Images/background_login1.jpg"))); // NOI18N
        jLabel10.setText("jLabel1");
        Panelsignup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        Container.add(Panelsignup, "card3");

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            pSm = conn.prepareCall("SELECT * from users where username=? and passwd=? and check_admin=?");
            pSm.setString(1, username.getText().toString());
            pSm.setString(2, passwd.getText().toString());
            pSm.setString(3, "1");
            rs = pSm.executeQuery();
            usernamee = username.getText().toString();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Login is success");
                HomeAdmin ha = new HomeAdmin();
                ha.usernamelogin.setText(this.username.getText().toString());
                ha.setVisible(true);
                ha.pack();
                ha.setLocationRelativeTo(null);
                ha.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } else {
                pSm = conn.prepareCall("SELECT * from users where username=? and passwd=? and check_admin=?");
                pSm.setString(1, username.getText().toString());
                pSm.setString(2, passwd.getText().toString());
                pSm.setString(3, "0");
                rs = pSm.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login is success");
                    HomeUser hu = new HomeUser();
                    hu.lbNameuser.setText(this.username.getText().toString());
                    hu.lbNameuser1.setText("Xin chào " + this.username.getText().toString() + ",");
                    hu.getUser(this.username.getText().toString());
                    hu.setTichDiem(this.username.getText().toString());
                    hu.setVisible(true);
                    hu.pack();
                    hu.setLocationRelativeTo(null);
                    hu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login is not success");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Server error");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                pSm = conn.prepareCall("SELECT * from users where username=? and passwd=? and check_admin=?");
                pSm.setString(1, username.getText().toString());
                pSm.setString(2, passwd.getText().toString());
                pSm.setString(3, "1");
                rs = pSm.executeQuery();
                usernamee = username.getText().toString();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login is success");
                    HomeAdmin ha = new HomeAdmin();
                    ha.usernamelogin.setText(this.username.getText().toString());
                    ha.setVisible(true);
                    ha.pack();
                    ha.setLocationRelativeTo(null);
                    ha.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } else {
                    pSm = conn.prepareCall("SELECT * from users where username=? and passwd=? and check_admin=?");
                    pSm.setString(1, username.getText().toString());
                    pSm.setString(2, passwd.getText().toString());
                    pSm.setString(3, "0");
                    rs = pSm.executeQuery();
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Login is success");
                        HomeUser hu = new HomeUser();
                        hu.lbNameuser.setText(this.username.getText().toString());
                        hu.lbNameuser1.setText("Xin chào " + this.username.getText().toString() + ",");
                        hu.getUser(this.username.getText().toString());
                        hu.setTichDiem(this.username.getText().toString());
                        hu.setVisible(true);
                        hu.pack();
                        hu.setLocationRelativeTo(null);
                        hu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Login is not success");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Server error");
            }
        }

    }//GEN-LAST:event_passwdKeyPressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        switchPanel(Panelsignup);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void lbUsernameSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbUsernameSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbUsernameSignupActionPerformed

    private void lbPassSignup2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbPassSignup2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (lbUsernameSignup.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
            } else if (lbPassSignup.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
            } else if (lbPassSignup2.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
            } else if (!lbPassSignup2.getText().equals(lbPassSignup.getText())) {
                JOptionPane.showMessageDialog(this, "2 mật khẩu phải giống nhau");
            } else if (lbUsernameSignup.getText().length() >= 16) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản phải nhỏ hơn 16 kí tự");
            } else if (lbPassSignup.getText().length() < 3) {
                JOptionPane.showMessageDialog(this, "Mật khẩu phải nhiều hơn 3 kí tự");
            } else {
                PreparedStatement pSm = null;
                try {
                    pSm = conn.prepareStatement("insert into users(username,passwd) values(?,?)");
                    pSm.setString(1, lbUsernameSignup.getText().toString());
                    pSm.setString(2, lbPassSignup.getText().toString());
                    pSm.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Đăng ký thành công");
                    HomeUser homeuser = new HomeUser();
                    homeuser.lbNameuser.setText(this.lbUsernameSignup.getText().toString());
                    homeuser.lbNameuser1.setText("Xin chào " + this.lbUsernameSignup.getText().toString() + ",");
                    homeuser.getUser(this.lbUsernameSignup.getText().toString());
                    homeuser.setTichDiem(this.username.getText().toString());
                    homeuser.setVisible(true);
                    homeuser.pack();
                    homeuser.setLocationRelativeTo(null);
                    homeuser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Tên tài khoản đã có người đăng ký");
                } finally {
                    //Giai phong
                    if (pSm != null) {
                        try {
                            pSm.close();
                        } catch (SQLException sqlEx) {
                        }
                        pSm = null;
                    }
                }

            }
        }
    }//GEN-LAST:event_lbPassSignup2KeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        switchPanel(Panellogin);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void lbPassSignupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbPassSignupKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbPassSignupKeyPressed

    private void btnSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignupMouseClicked
        // TODO add your handling code here:
        if (lbUsernameSignup.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
        } else if (lbPassSignup.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
        } else if (lbPassSignup2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Phải nhập đủ thông tin đăng ký");
        } else if (!lbPassSignup2.getText().equals(lbPassSignup.getText())) {
            JOptionPane.showMessageDialog(this, "2 mật khẩu phải giống nhau");
        } else if (lbUsernameSignup.getText().length() >= 16) {
            JOptionPane.showMessageDialog(this, "Tên tài khoản phải nhỏ hơn 16 kí tự");
        } else if (lbPassSignup.getText().length() < 3) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải nhiều hơn 3 kí tự");
        } else {
            PreparedStatement pSm = null;
            try {
                pSm = conn.prepareStatement("insert into users(username,passwd) values(?,?)");
                pSm.setString(1, lbUsernameSignup.getText().toString());
                pSm.setString(2, lbPassSignup.getText().toString());
                pSm.executeUpdate();
                JOptionPane.showMessageDialog(this, "Đăng ký thành công");
                HomeUser homeuser = new HomeUser();
                homeuser.lbNameuser.setText(this.lbUsernameSignup.getText().toString());
                homeuser.lbNameuser1.setText("Xin chào " + this.lbUsernameSignup.getText().toString() + ",");
                homeuser.getUser(this.lbUsernameSignup.getText().toString());
                homeuser.setTichDiem(this.username.getText().toString());
                homeuser.setVisible(true);
                homeuser.pack();
                homeuser.setLocationRelativeTo(null);
                homeuser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản đã có người đăng ký");
            } finally {
                //Giai phong
                if (pSm != null) {
                    try {
                        pSm.close();
                    } catch (SQLException sqlEx) {
                    }
                    pSm = null;
                }
            }

        }
    }//GEN-LAST:event_btnSignupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Panellogin;
    private javax.swing.JPanel Panelsignup;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField lbPassSignup;
    private javax.swing.JPasswordField lbPassSignup2;
    private javax.swing.JTextField lbUsernameSignup;
    private javax.swing.JPasswordField passwd;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
